### PR TITLE
feat!: introduce v3 of API

### PR DESCRIPTION
**Pull request by JustinBeckwith**
@bcoe @sofisl after going through this - the thought occurs to me - maybe we shouldn't.  The name of this package is `@google-cloud/resource`, even though it's the `resourcemanager` API.  This maybe wouldn't be a problem if not for the fact that there's also a `resourcesettings` API.  We could take the approach of dropping this as a semver major change, including a migration guide, and using the same name.  Alternatively - we could mark this repository as deprecated (it never left alpha), and introduce a new `resourcemanager` repository.  

Not sure which is the right approach, but interested in opinions!

### CODE REVIEW

**Comment by sofisl** [comment]
I think I prefer the second option as the implementer, but also flexible to what is better for the library. If I'm understanding correctly, the reason we're doing this is to rename its package?

**Comment by bcoe** [comment]
@JustinBeckwith @sofisl, given this never left alpha, and has a small user base, could we just rename this repository, rather than creating a new one and deprecating?

**Comment by JustinBeckwith** [comment]
I'm less concerned with the repository name than the package name.  I am fine with renaming the repo - what do you think we should do with the package?

**Comment by bcoe** [comment]
@sofisl @JustinBeckwith I'd advocate we name it `@google-cloud/resource-manager`, and also rename this repo to `nodejs-resource-manager`, we can call this a `v0.1.0` release of `@google-cloud/resource-manager`.

**Comment by JustinBeckwith** [comment]
Sounds good to me.  In that case though - we need to keep the `@google-cloud/resource` npm module around, and explicitly deprecate it ... right?  Otherwise, it's completely abandoned.  We would need to update this code to add a deprecation warning, and point users towards the new shiny module.  If we go down that road, I would suggest we drop this PR and instead create a new repository.

Thoughts?

**Comment by bcoe** [comment]
@JustinBeckwith I'm just not seeing the point to a new repository, we switched the name of `dialogflow` to `@google-cloud/dialogflow` for consistency, and just added a warning in the README.

https://github.com/googleapis/nodejs-dialogflow

I think it creates less confusion not to have a `nodejs-resource` repo, and a `nodejs-resource-manager`, so I'm saying:

1. rename this repo to `resource-manager`.
2. add a similar note to the top of the README, regarding the name change.
3. land a PR that adds the v3 surface.
4. still deprecate the old npm module, in a major.

**Comment by JustinBeckwith** [comment]
Sounds good to me!

**Comment by JustinBeckwith** [comment]
@bcoe @sofisl do we still want this PR, or are we taking a different approach?  Happy to close or clean up or whatever y'all decide :)

**Pull request closed without merging**
