### PR TITLE
Update google-auto-auth

### PR DESCRIPTION
**Pull request by stephenplusplus**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@alexander-fenster @callmehiphop -- CI lint is getting this error:

```
#!/bin/bash -eo pipefail
npm run lint

> @google-cloud/resource@0.8.1 lint /root/project
> repo-tools lint --cmd eslint -- src/ samples/ system-test/ test/

lint: Linting files in: /root/project
lint: Running: eslint src/ samples/ system-test/ test/

/root/project/system-test/resource.js
  22:26  error  "google-auto-auth" is not found  node/no-missing-require
```
https://circleci.com/gh/googleapis/nodejs-resource/643

Do you know how to fix?

**Comment by alexander-fenster** [comment]
I do! Just copied it to another PR but I can copy here as well! Cmd+C Cmd+V just works :)
```sh
rm -rf node_modules package-lock.json samples/package-lock.json samples/node_modules
npm install && npm link && cd samples && npm link ../ && npm install && cd .. && npm run lint
git add package-lock.json samples/package-lock.json
```

**Comment by alexander-fenster** [comment]
The idea is, when main packages' dependencies change and `package-lock.json` is regenerated, we need to take care of samples' `package-lock.json` as well. It looks like a kind of downside of having `package-lock.json` checked in (heh), but let's live with it for a while and we'll see how we can improve it.

**Comment by stephenplusplus** [comment]
Thanks!

**Pull request merged**
